package com.adventofcode;

import java.util.Arrays;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class Question05Test {

    public static final String ANSWER_1 = "SHQWSRBDL";
    public static final String ANSWER_2 = "CDTQZHBRS";
    String pilesSource = "HCR,BJHLSF,RMDHJTQ,SGRHZBJ,RPFZTDCB,THCG,SNVZBPWL,RJQGC,LDTRHPFS";
    String[] piles = pilesSource.split(",");

    String source;
    String[] instructions;
    Pattern pattern = Pattern.compile("move (\\d+) from (\\d+) to (\\d+)");

    private class Instruction {

        Instruction(int amountToMove, int startPileNumber, int endPileNumber) {
            this.amountToMove = amountToMove;
            this.startPileNumber = startPileNumber;
            this.endPileNumber = endPileNumber;
        }

        Instruction(String input) {
            Matcher matcher = pattern.matcher(input);
            if (matcher.find()) {
                int amountToMove = Integer.parseInt(matcher.group(1));
                int startPileNumber = Integer.parseInt(matcher.group(2));
                int endPileNumber = Integer.parseInt(matcher.group(3));
                this.amountToMove = amountToMove;
                this.startPileNumber = startPileNumber;
                this.endPileNumber = endPileNumber;
            }
        }

        int amountToMove;
        int startPileNumber;
        int endPileNumber;
    }


    @BeforeEach
    void setUpSource() {
        source = "move 8 from 7 to 1\n"
            + "move 9 from 1 to 9\n"
            + "move 4 from 5 to 4\n"
            + "move 4 from 6 to 1\n"
            + "move 3 from 8 to 5\n"
            + "move 6 from 5 to 9\n"
            + "move 1 from 5 to 1\n"
            + "move 4 from 4 to 9\n"
            + "move 7 from 3 to 7\n"
            + "move 6 from 7 to 3\n"
            + "move 1 from 8 to 7\n"
            + "move 2 from 7 to 6\n"
            + "move 1 from 8 to 9\n"
            + "move 1 from 6 to 3\n"
            + "move 4 from 3 to 5\n"
            + "move 5 from 1 to 3\n"
            + "move 1 from 1 to 8\n"
            + "move 2 from 3 to 4\n"
            + "move 1 from 4 to 1\n"
            + "move 7 from 9 to 2\n"
            + "move 1 from 6 to 3\n"
            + "move 2 from 1 to 9\n"
            + "move 20 from 9 to 7\n"
            + "move 6 from 4 to 9\n"
            + "move 1 from 2 to 9\n"
            + "move 6 from 9 to 4\n"
            + "move 1 from 4 to 6\n"
            + "move 1 from 8 to 6\n"
            + "move 1 from 4 to 7\n"
            + "move 5 from 2 to 3\n"
            + "move 2 from 6 to 4\n"
            + "move 3 from 9 to 5\n"
            + "move 5 from 3 to 5\n"
            + "move 3 from 3 to 8\n"
            + "move 3 from 5 to 6\n"
            + "move 1 from 9 to 8\n"
            + "move 5 from 4 to 5\n"
            + "move 3 from 4 to 9\n"
            + "move 1 from 8 to 2\n"
            + "move 2 from 8 to 2\n"
            + "move 11 from 5 to 6\n"
            + "move 16 from 7 to 1\n"
            + "move 2 from 1 to 7\n"
            + "move 14 from 6 to 1\n"
            + "move 11 from 1 to 6\n"
            + "move 2 from 1 to 4\n"
            + "move 4 from 3 to 4\n"
            + "move 9 from 2 to 4\n"
            + "move 2 from 4 to 8\n"
            + "move 2 from 5 to 3\n"
            + "move 9 from 4 to 7\n"
            + "move 2 from 3 to 2\n"
            + "move 1 from 2 to 7\n"
            + "move 1 from 8 to 4\n"
            + "move 4 from 1 to 4\n"
            + "move 1 from 9 to 1\n"
            + "move 7 from 4 to 7\n"
            + "move 2 from 6 to 5\n"
            + "move 1 from 8 to 6\n"
            + "move 1 from 4 to 2\n"
            + "move 10 from 1 to 6\n"
            + "move 5 from 7 to 3\n"
            + "move 1 from 4 to 7\n"
            + "move 2 from 1 to 2\n"
            + "move 2 from 2 to 4\n"
            + "move 4 from 3 to 4\n"
            + "move 18 from 7 to 6\n"
            + "move 6 from 6 to 4\n"
            + "move 1 from 7 to 4\n"
            + "move 1 from 7 to 6\n"
            + "move 11 from 4 to 5\n"
            + "move 14 from 5 to 9\n"
            + "move 1 from 8 to 7\n"
            + "move 8 from 6 to 2\n"
            + "move 2 from 4 to 5\n"
            + "move 7 from 9 to 1\n"
            + "move 6 from 9 to 7\n"
            + "move 5 from 1 to 8\n"
            + "move 1 from 3 to 6\n"
            + "move 10 from 6 to 3\n"
            + "move 1 from 9 to 6\n"
            + "move 1 from 5 to 4\n"
            + "move 4 from 3 to 8\n"
            + "move 1 from 5 to 9\n"
            + "move 9 from 2 to 3\n"
            + "move 1 from 9 to 5\n"
            + "move 4 from 8 to 4\n"
            + "move 1 from 5 to 3\n"
            + "move 5 from 8 to 7\n"
            + "move 5 from 7 to 2\n"
            + "move 3 from 4 to 1\n"
            + "move 8 from 6 to 5\n"
            + "move 1 from 7 to 9\n"
            + "move 4 from 1 to 3\n"
            + "move 2 from 4 to 6\n"
            + "move 5 from 5 to 2\n"
            + "move 4 from 6 to 9\n"
            + "move 1 from 1 to 2\n"
            + "move 1 from 5 to 6\n"
            + "move 7 from 2 to 8\n"
            + "move 5 from 6 to 8\n"
            + "move 4 from 7 to 9\n"
            + "move 15 from 3 to 9\n"
            + "move 1 from 7 to 3\n"
            + "move 1 from 5 to 3\n"
            + "move 6 from 2 to 6\n"
            + "move 1 from 5 to 2\n"
            + "move 2 from 3 to 9\n"
            + "move 1 from 6 to 8\n"
            + "move 5 from 8 to 9\n"
            + "move 2 from 3 to 8\n"
            + "move 3 from 3 to 6\n"
            + "move 11 from 9 to 4\n"
            + "move 1 from 2 to 1\n"
            + "move 2 from 8 to 4\n"
            + "move 1 from 1 to 4\n"
            + "move 7 from 4 to 7\n"
            + "move 9 from 6 to 3\n"
            + "move 4 from 7 to 8\n"
            + "move 4 from 7 to 6\n"
            + "move 19 from 9 to 4\n"
            + "move 7 from 8 to 5\n"
            + "move 5 from 3 to 6\n"
            + "move 6 from 6 to 9\n"
            + "move 3 from 3 to 5\n"
            + "move 1 from 3 to 9\n"
            + "move 8 from 4 to 5\n"
            + "move 2 from 9 to 6\n"
            + "move 3 from 8 to 2\n"
            + "move 1 from 8 to 4\n"
            + "move 1 from 2 to 5\n"
            + "move 19 from 4 to 1\n"
            + "move 2 from 5 to 7\n"
            + "move 2 from 2 to 4\n"
            + "move 13 from 5 to 2\n"
            + "move 1 from 5 to 1\n"
            + "move 2 from 6 to 9\n"
            + "move 1 from 8 to 7\n"
            + "move 9 from 9 to 3\n"
            + "move 2 from 3 to 8\n"
            + "move 1 from 4 to 2\n"
            + "move 5 from 6 to 7\n"
            + "move 1 from 4 to 6\n"
            + "move 2 from 8 to 7\n"
            + "move 7 from 1 to 5\n"
            + "move 1 from 6 to 7\n"
            + "move 10 from 1 to 8\n"
            + "move 1 from 1 to 3\n"
            + "move 1 from 1 to 2\n"
            + "move 6 from 5 to 3\n"
            + "move 4 from 5 to 3\n"
            + "move 5 from 7 to 1\n"
            + "move 3 from 1 to 2\n"
            + "move 4 from 7 to 5\n"
            + "move 8 from 3 to 6\n"
            + "move 2 from 1 to 7\n"
            + "move 4 from 5 to 8\n"
            + "move 7 from 3 to 5\n"
            + "move 3 from 7 to 2\n"
            + "move 1 from 7 to 3\n"
            + "move 12 from 2 to 8\n"
            + "move 23 from 8 to 2\n"
            + "move 16 from 2 to 6\n"
            + "move 1 from 9 to 6\n"
            + "move 7 from 5 to 7\n"
            + "move 7 from 2 to 4\n"
            + "move 2 from 3 to 8\n"
            + "move 1 from 1 to 9\n"
            + "move 5 from 8 to 1\n"
            + "move 2 from 3 to 9\n"
            + "move 2 from 7 to 1\n"
            + "move 4 from 1 to 3\n"
            + "move 4 from 7 to 2\n"
            + "move 2 from 1 to 4\n"
            + "move 11 from 2 to 9\n"
            + "move 3 from 3 to 4\n"
            + "move 1 from 9 to 1\n"
            + "move 2 from 2 to 7\n"
            + "move 4 from 4 to 8\n"
            + "move 2 from 9 to 5\n"
            + "move 2 from 5 to 7\n"
            + "move 4 from 4 to 6\n"
            + "move 1 from 3 to 8\n"
            + "move 1 from 9 to 8\n"
            + "move 4 from 4 to 2\n"
            + "move 2 from 1 to 3\n"
            + "move 1 from 8 to 4\n"
            + "move 2 from 3 to 5\n"
            + "move 3 from 9 to 7\n"
            + "move 2 from 8 to 9\n"
            + "move 1 from 9 to 6\n"
            + "move 2 from 7 to 3\n"
            + "move 2 from 8 to 1\n"
            + "move 1 from 4 to 9\n"
            + "move 18 from 6 to 2\n"
            + "move 1 from 6 to 5\n"
            + "move 1 from 5 to 9\n"
            + "move 18 from 2 to 3\n"
            + "move 1 from 8 to 7\n"
            + "move 2 from 5 to 9\n"
            + "move 1 from 1 to 4\n"
            + "move 3 from 2 to 1\n"
            + "move 9 from 9 to 4\n"
            + "move 7 from 4 to 6\n"
            + "move 2 from 7 to 3\n"
            + "move 2 from 4 to 9\n"
            + "move 7 from 6 to 7\n"
            + "move 3 from 7 to 2\n"
            + "move 7 from 6 to 3\n"
            + "move 2 from 6 to 9\n"
            + "move 24 from 3 to 9\n"
            + "move 2 from 6 to 8\n"
            + "move 1 from 4 to 2\n"
            + "move 2 from 8 to 5\n"
            + "move 31 from 9 to 3\n"
            + "move 6 from 7 to 4\n"
            + "move 35 from 3 to 7\n"
            + "move 1 from 1 to 8\n"
            + "move 1 from 5 to 7\n"
            + "move 1 from 5 to 4\n"
            + "move 1 from 3 to 9\n"
            + "move 1 from 8 to 2\n"
            + "move 3 from 1 to 7\n"
            + "move 7 from 4 to 5\n"
            + "move 1 from 9 to 8\n"
            + "move 4 from 5 to 6\n"
            + "move 2 from 5 to 2\n"
            + "move 6 from 2 to 5\n"
            + "move 2 from 5 to 7\n"
            + "move 2 from 2 to 1\n"
            + "move 2 from 5 to 4\n"
            + "move 1 from 8 to 4\n"
            + "move 3 from 4 to 6\n"
            + "move 4 from 6 to 7\n"
            + "move 1 from 5 to 2\n"
            + "move 2 from 6 to 9\n"
            + "move 1 from 6 to 4\n"
            + "move 1 from 4 to 8\n"
            + "move 2 from 9 to 6\n"
            + "move 1 from 8 to 9\n"
            + "move 34 from 7 to 9\n"
            + "move 6 from 7 to 3\n"
            + "move 1 from 7 to 2\n"
            + "move 1 from 5 to 8\n"
            + "move 1 from 8 to 6\n"
            + "move 6 from 7 to 4\n"
            + "move 1 from 7 to 3\n"
            + "move 7 from 3 to 5\n"
            + "move 6 from 4 to 6\n"
            + "move 31 from 9 to 1\n"
            + "move 3 from 5 to 7\n"
            + "move 24 from 1 to 3\n"
            + "move 1 from 2 to 4\n"
            + "move 3 from 9 to 1\n"
            + "move 14 from 3 to 5\n"
            + "move 1 from 4 to 3\n"
            + "move 1 from 9 to 7\n"
            + "move 8 from 3 to 7\n"
            + "move 1 from 2 to 9\n"
            + "move 7 from 1 to 5\n"
            + "move 3 from 6 to 8\n"
            + "move 3 from 6 to 1\n"
            + "move 1 from 1 to 3\n"
            + "move 4 from 3 to 2\n"
            + "move 4 from 2 to 3\n"
            + "move 2 from 5 to 1\n"
            + "move 9 from 7 to 4\n"
            + "move 1 from 6 to 5\n"
            + "move 1 from 1 to 7\n"
            + "move 3 from 8 to 9\n"
            + "move 5 from 4 to 2\n"
            + "move 3 from 2 to 3\n"
            + "move 1 from 2 to 3\n"
            + "move 2 from 4 to 1\n"
            + "move 2 from 9 to 4\n"
            + "move 1 from 9 to 3\n"
            + "move 1 from 6 to 1\n"
            + "move 1 from 9 to 6\n"
            + "move 25 from 5 to 4\n"
            + "move 4 from 1 to 9\n"
            + "move 2 from 3 to 7\n"
            + "move 2 from 6 to 9\n"
            + "move 2 from 9 to 5\n"
            + "move 6 from 7 to 1\n"
            + "move 5 from 3 to 6\n"
            + "move 10 from 4 to 3\n"
            + "move 10 from 4 to 8\n"
            + "move 2 from 4 to 2\n"
            + "move 5 from 1 to 9\n"
            + "move 2 from 6 to 4\n"
            + "move 6 from 9 to 6\n"
            + "move 7 from 6 to 4\n"
            + "move 3 from 9 to 4\n"
            + "move 3 from 2 to 4\n"
            + "move 4 from 3 to 8\n"
            + "move 2 from 5 to 3\n"
            + "move 10 from 4 to 9\n"
            + "move 4 from 9 to 7\n"
            + "move 5 from 9 to 5\n"
            + "move 4 from 5 to 1\n"
            + "move 9 from 4 to 6\n"
            + "move 10 from 1 to 3\n"
            + "move 1 from 5 to 4\n"
            + "move 3 from 4 to 5\n"
            + "move 2 from 5 to 7\n"
            + "move 1 from 7 to 3\n"
            + "move 1 from 6 to 9\n"
            + "move 11 from 8 to 6\n"
            + "move 14 from 6 to 5\n"
            + "move 1 from 4 to 7\n"
            + "move 7 from 5 to 3\n"
            + "move 3 from 5 to 4\n"
            + "move 2 from 9 to 5\n"
            + "move 2 from 4 to 3\n"
            + "move 2 from 7 to 4\n"
            + "move 11 from 3 to 9\n"
            + "move 2 from 8 to 2\n"
            + "move 2 from 2 to 3\n"
            + "move 1 from 8 to 2\n"
            + "move 1 from 2 to 9\n"
            + "move 3 from 4 to 5\n"
            + "move 2 from 6 to 9\n"
            + "move 1 from 1 to 8\n"
            + "move 10 from 9 to 7\n"
            + "move 2 from 9 to 3\n"
            + "move 23 from 3 to 9\n"
            + "move 4 from 6 to 4\n"
            + "move 9 from 5 to 6\n"
            + "move 1 from 5 to 3\n"
            + "move 5 from 6 to 7\n"
            + "move 1 from 1 to 7\n"
            + "move 1 from 3 to 9\n"
            + "move 4 from 6 to 7\n"
            + "move 1 from 8 to 7\n"
            + "move 1 from 7 to 5\n"
            + "move 1 from 5 to 1\n"
            + "move 12 from 7 to 6\n"
            + "move 9 from 9 to 3\n"
            + "move 6 from 6 to 4\n"
            + "move 8 from 7 to 3\n"
            + "move 3 from 7 to 4\n"
            + "move 6 from 3 to 1\n"
            + "move 10 from 4 to 8\n"
            + "move 10 from 8 to 7\n"
            + "move 2 from 3 to 7\n"
            + "move 9 from 3 to 8\n"
            + "move 2 from 6 to 3\n"
            + "move 10 from 7 to 1\n"
            + "move 3 from 4 to 6\n"
            + "move 5 from 8 to 5\n"
            + "move 3 from 5 to 7\n"
            + "move 1 from 3 to 2\n"
            + "move 1 from 2 to 6\n"
            + "move 6 from 9 to 1\n"
            + "move 12 from 1 to 3\n"
            + "move 3 from 6 to 9\n"
            + "move 3 from 1 to 7\n"
            + "move 1 from 3 to 2\n"
            + "move 7 from 1 to 7\n"
            + "move 1 from 2 to 7\n"
            + "move 2 from 6 to 4\n"
            + "move 1 from 4 to 5\n"
            + "move 3 from 8 to 7\n"
            + "move 2 from 6 to 3\n"
            + "move 2 from 6 to 1\n"
            + "move 1 from 3 to 8\n"
            + "move 5 from 3 to 4\n"
            + "move 2 from 8 to 5\n"
            + "move 14 from 7 to 4\n"
            + "move 1 from 3 to 2\n"
            + "move 1 from 3 to 7\n"
            + "move 7 from 7 to 4\n"
            + "move 2 from 5 to 3\n"
            + "move 2 from 1 to 4\n"
            + "move 9 from 4 to 6\n"
            + "move 1 from 1 to 2\n"
            + "move 4 from 9 to 4\n"
            + "move 8 from 9 to 3\n"
            + "move 2 from 2 to 7\n"
            + "move 13 from 4 to 8\n"
            + "move 4 from 4 to 1\n"
            + "move 2 from 7 to 6\n"
            + "move 12 from 3 to 2\n"
            + "move 11 from 2 to 9\n"
            + "move 6 from 4 to 9\n"
            + "move 18 from 9 to 4\n"
            + "move 2 from 1 to 6\n"
            + "move 6 from 8 to 1\n"
            + "move 13 from 6 to 5\n"
            + "move 8 from 4 to 5\n"
            + "move 1 from 2 to 9\n"
            + "move 8 from 1 to 4\n"
            + "move 7 from 4 to 8\n"
            + "move 4 from 3 to 5\n"
            + "move 10 from 8 to 5\n"
            + "move 13 from 5 to 8\n"
            + "move 12 from 4 to 5\n"
            + "move 2 from 9 to 8\n"
            + "move 29 from 5 to 9\n"
            + "move 24 from 9 to 2\n"
            + "move 23 from 2 to 4\n"
            + "move 5 from 9 to 2\n"
            + "move 7 from 5 to 7\n"
            + "move 1 from 5 to 1\n"
            + "move 7 from 4 to 8\n"
            + "move 14 from 8 to 1\n"
            + "move 5 from 2 to 6\n"
            + "move 16 from 4 to 7\n"
            + "move 8 from 1 to 6\n"
            + "move 1 from 2 to 8\n"
            + "move 20 from 7 to 6\n"
            + "move 11 from 6 to 4\n"
            + "move 3 from 1 to 5\n"
            + "move 3 from 4 to 3\n"
            + "move 8 from 4 to 9\n"
            + "move 8 from 6 to 1\n"
            + "move 2 from 1 to 4\n"
            + "move 3 from 5 to 2\n"
            + "move 12 from 8 to 2\n"
            + "move 1 from 7 to 1\n"
            + "move 1 from 3 to 5\n"
            + "move 1 from 7 to 8\n"
            + "move 1 from 7 to 3\n"
            + "move 12 from 2 to 8\n"
            + "move 13 from 6 to 4\n"
            + "move 2 from 1 to 9\n"
            + "move 3 from 2 to 6\n"
            + "move 3 from 9 to 7\n"
            + "move 5 from 9 to 1\n"
            + "move 4 from 6 to 4\n"
            + "move 2 from 3 to 6\n"
            + "move 1 from 5 to 9\n"
            + "move 1 from 6 to 7\n"
            + "move 9 from 1 to 5\n"
            + "move 11 from 8 to 3\n"
            + "move 1 from 6 to 8\n"
            + "move 3 from 7 to 1\n"
            + "move 1 from 8 to 7\n"
            + "move 2 from 8 to 9\n"
            + "move 7 from 1 to 2\n"
            + "move 17 from 4 to 7\n"
            + "move 1 from 8 to 6\n"
            + "move 4 from 7 to 2\n"
            + "move 4 from 9 to 7\n"
            + "move 4 from 2 to 3\n"
            + "move 1 from 1 to 4\n"
            + "move 2 from 4 to 3\n"
            + "move 9 from 5 to 4\n"
            + "move 1 from 6 to 8\n"
            + "move 6 from 2 to 1\n"
            + "move 5 from 1 to 9\n"
            + "move 9 from 4 to 3\n"
            + "move 1 from 4 to 6\n"
            + "move 2 from 9 to 7\n"
            + "move 1 from 1 to 5\n"
            + "move 1 from 2 to 7\n"
            + "move 1 from 8 to 9\n"
            + "move 1 from 6 to 8\n"
            + "move 1 from 5 to 4\n"
            + "move 1 from 8 to 7\n"
            + "move 23 from 3 to 7\n"
            + "move 36 from 7 to 6\n"
            + "move 33 from 6 to 1\n"
            + "move 1 from 4 to 8\n"
            + "move 7 from 1 to 5\n"
            + "move 1 from 8 to 1\n"
            + "move 3 from 7 to 2\n"
            + "move 24 from 1 to 3\n"
            + "move 7 from 7 to 3\n"
            + "move 3 from 5 to 1\n"
            + "move 4 from 5 to 3\n"
            + "move 1 from 9 to 8\n"
            + "move 2 from 9 to 6\n"
            + "move 1 from 8 to 5\n"
            + "move 3 from 2 to 5\n"
            + "move 30 from 3 to 5\n"
            + "move 1 from 6 to 7\n"
            + "move 6 from 1 to 8\n"
            + "move 7 from 3 to 2\n"
            + "move 1 from 7 to 5\n"
            + "move 2 from 3 to 2\n"
            + "move 2 from 6 to 8\n"
            + "move 1 from 6 to 1\n"
            + "move 7 from 5 to 8\n"
            + "move 8 from 8 to 7\n"
            + "move 20 from 5 to 8\n"
            + "move 2 from 9 to 7\n"
            + "move 8 from 2 to 1\n"
            + "move 7 from 7 to 3\n"
            + "move 1 from 2 to 1\n"
            + "move 3 from 7 to 9\n"
            + "move 4 from 8 to 3\n"
            + "move 5 from 5 to 6\n"
            + "move 1 from 5 to 9\n"
            + "move 4 from 9 to 4\n"
            + "move 1 from 5 to 9\n"
            + "move 2 from 3 to 6\n"
            + "move 1 from 5 to 8\n"
            + "move 7 from 6 to 3\n"
            + "move 1 from 4 to 1\n"
            + "move 7 from 3 to 2\n"
            + "move 3 from 3 to 5\n"
            + "move 2 from 4 to 7";
    }

    @BeforeEach
    void setUp() {
        instructions = source.split("\n");
    }

    @Test
    void question1() {
        Arrays.stream(instructions).forEach(this::processInstructionOneAtATime);

        String result = getTopBoxOfAllPiles();
        assertThat(result).isEqualTo(ANSWER_1);
    }

    @Test
    void question2() {
        Arrays.stream(instructions).forEach(this::processInstructionCanLiftMultiple);

        String result = getTopBoxOfAllPiles();
        assertThat(result).isEqualTo(ANSWER_2);
    }


    void processInstructionOneAtATime(String input) {
        Instruction instruction = new Instruction(input);

        for (int j = instruction.amountToMove; j > 0; j--) {
            moveBoxOneAtATime(instruction.startPileNumber, instruction.endPileNumber);
        }
    }

    void processInstructionCanLiftMultiple(String input) {
        Instruction instruction = new Instruction(input);
        moveBoxes(instruction.startPileNumber, instruction.endPileNumber, instruction.amountToMove);

    }

    void moveBoxes(int startPileNumber, int endPileNumber, int amountToMove) {
        var startPile = piles[startPileNumber - 1];
        var endPile = piles[endPileNumber - 1];
        var newStartPile = removeTopN(startPile, amountToMove);
        var newEndPile = push(endPile, getBoxesToMove(startPile, amountToMove));
        piles[startPileNumber - 1] = newStartPile;
        piles[endPileNumber - 1] = newEndPile;
    }

    void moveBoxOneAtATime(int startPileNumber, int endPileNumber) {
        moveBoxes(startPileNumber, endPileNumber, 1);
    }

    private String removeTopN(String pile, int amount) {
        return pile.substring(0, pile.length() - amount);
    }

    private String getBoxesToMove(String pile, int amount) {
        return pile.substring(pile.length() - amount);
    }

    private String push(String pile, String box) {
        return pile + box;
    }

    private String getTopBoxOfAllPiles() {
        StringBuilder result = new StringBuilder();
        Arrays.stream(piles).forEach(pile -> result.append(pile.charAt(pile.length() - 1)));
        return result.toString();
    }


}
